wok = Restaurant.create(name: "Wok", address: "Barcelona", category: "chinese")
napoli = Restaurant.create(name: "Bella Napoli", address: "Barcelona", category: "italian")
lao = Restaurant.create(name: "Lao Lane Xang", address: "Paris", category: "chinese")
bouillon = Restaurant.create(name: "Bouillon Chartier", address: "Paris", category: "french")
leon = Restaurant.create(name: "Leon de Bruxelle", address: "Bruxelle", category: "belgian")
